### ISSUE TITLE
[Bug]: Plugin incompatible with latest version of Zotero

### ISSUE THREAD

**Issue by dhutton2002** [ImperialSquid/zotero-zotts#123]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same bug report. (Note - if the bug report is about ZoTTS failing to start, please ignore this step and open a report anyway, start up failures can have various causes so it's easier to have separate issues for each, *especially* Linux users)
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I have described the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain paper, I will include its details.

### Zotero version

6.0.36

### ZoTTS version

1.3.0

### OS

Windows

### OS (specific)

Windows 11

### Steps to reproduce

1. Download the .xpi file from the latest release (https://github.com/ImperialSquid/zotero-zotts/releases)
2. Open Zotero and select Tools > Add-ons > Gear icon > Install Add-on From File
3. Select the downloaded .xpi file

### Expected behaviour

Install the plugin

### Actual behaviour

![Screenshot 2024-10-21 111351](https://github.com/user-attachments/assets/3dacbf88-3a02-4c05-9a95-e9fa23c95e88)

Error message: "The add-on "%S" could not be installed. It may be incompatible with this version of Zotero."

**Comment by ImperialSquid** [comment]
Hi @dhutton2002, thanks for your bug report. 

ZoTTS is only compatible with Zotero 7+, so this is intended behaviour. 

If you want to use ZoTTS you'll also need to upgrade to the latest version of Zotero (version 7), available [here](https://www.zotero.org/download/). Sorry for any inconvenience.

---

Zotero 6 and 7 work very differently under the hood due to a major overhaul of how the program runs. 

As part of the development I was weighing up whether to develop for compatibility with both versions or just the newer version, since Zotero 7 entered beta at around the same time as ZoTTS was getting ready for the first release, and on the advice of a few of the Zotero devs, ZoTTS is only compatible with versions 7+. 

Sorry again for any inconvenience.

**Comment by ImperialSquid** [comment]
No worries!

Let me know if you run into any more issues, have any feature requests, etc etc 😊
