### ISSUE TITLE
How usable is this?

### ISSUE THREAD

**Issue by antrmn** [ImperialSquid/zotero-zotts#58]
What progress has been made so far on this addon? What are the main obstacles or blockers facing this project?

Thank you in advance

**Comment by ImperialSquid** [comment]
Hi,

Thanks for your interest in this project!

Unfortunately due to a bunch of personal life and medical stuff getting in the way, ZoTTS got pushed way down my priority list last year. As such very little progress has been made that isn't already on GitHub.

However, most of those issues have now been resolved so I'm hoping to start this project up again soon!

Let me know here or by email if you have any other questions, I'll be closing the issue now.

**Comment by sstraume97** [comment]
Really looking forward to the addon being ready!

When I have to read many and long case papers the week before meetings, I often use TTS for the longest documents. Recitation is a feature I've really missed in Zotero! Today, I read and highlight the PDFs in Zotero, but also open up the PDF in Edge for reading. It's a clumsy solution.

So as long as Zotero is the best solution for my needs, switching programs is out of the question. So then, in the meantime, until ZoTTS is ready, I'll settle for using Edge...

Have [posted in the Zotero forum](https://forums.zotero.org/discussion/110797/zotts-text-to-speech-plugin) about the extension.
