### ISSUE TITLE
[Bug]: Pronounces "Å" as "A"

### ISSUE THREAD

**Issue by sstraume97** [ImperialSquid/zotero-zotts#87]
### Checklist

- [x] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I have described the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain paper, I will include its details.

### Zotero version

7.0.1 (64-bit)

### ZoTTS version

1.2.0

### OS

Windows

### OS (specific)

Windows 11

### Steps to reproduce

Read selected text in PDF ([Å.pdf](https://github.com/user-attachments/files/16676094/A.pdf)) and note (text "A, a, Å, å") aloud.

### Expected behaviour

Pronounce the letter "Å" correctly in PDFs (this is how Å is pronounced [LL-Q9043 (nor)-EdoAug-å.wav, Wikimedia Commons](https://upload.wikimedia.org/wikipedia/commons/3/3e/LL-Q9043_%28nor%29-EdoAug-%C3%A5.wav)).

### Actual behaviour

In PDFs, "Å" is pronounced as "A". In notes, the pronunciation is correct. 

Below is a screen recording from the reading:
- [Note](https://github.com/user-attachments/assets/508596a2-d680-475d-b5a4-e85e3dafcf14)
- [PDF](https://github.com/user-attachments/assets/172b1c2f-57d0-4cdc-89b6-6a1b84f26692)

**Comment by ImperialSquid** [comment]
Thanks for your bug report.

ZoTTS doesn't do any text encoding/editing, and the debug output shows it's speaking the text exactly as given with diacritics.

My guess is that it's a PDF encoding error, can you tell me which paper you were looking at when this first happened?

Also, during testing it seems like English TTS voices don't discriminate between A and Å, if you could let me know what voice you use that would be helpful.

**Comment by ImperialSquid** [comment]
I did some more investigating, and it looks like it is an encoding thing but only for (some of) _Zotero,_ not the PDF itself.

There are two ways to display a "Å" character it seems, either as one unicode item (which is pronounced correctly) or as a regular A with a diacritic separately (which is pronounced incorrectly, likely due to the TTS engine cleaning and/or ignoring it)

![Image showing two ways of encoding A with circle diacritic](https://github.com/user-attachments/assets/47768dde-bf14-4ff6-b8cd-56390857b885)

Interestingly, there are also multiple ways to select the text in a paper, and only some of them change the unicode encoding.

I'll open issues on the plugin toolkit ZoTTS uses, and on Zotero itself to let them know this is a thing.

In the meantime, I'll change how ZoTTS collects the selected text from the paper, so it uses a method that gives the unaltered version. Additionally, a future version of ZoTTS will let the user specify regex substitutions for the spoken text, and I'll make a note to add a built-in "unicode fixing" set of substitutions, just in case this bug should appear in a different way or be regressed on.

**Comment by ImperialSquid** [comment]
[Reported to Zotero team](https://forums.zotero.org/discussion/117218/bug-inconsistent-return-value-for-selected-text-depending-on-method#latest)

**Comment by sstraume97** [comment]
Nå fungerer det perfekt!
